import { note as n, option as o, beat as b, cap, prior } from "./schema.js";
const incident = (
  id,
  title,
  category,
  text,
  observation,
  left,
  right,
  extra = {},
) => ({
  id,
  title,
  kind: extra.kind || "ambient",
  category,
  privateTruth:
    "Observación local limitada; origen reservado. No implica progreso de un hilo mayor.",
  beats: [
    b(
      "encounter",
      text,
      [n("observed", observation, { legacy: false, ...extra.note })],
      o(
        left,
        extra.leftResult || "Conservas lo observado sin atribuirle una causa.",
        null,
        { status: "documented" },
      ),
      o(
        right,
        extra.rightResult ||
          "La vida cotidiana continúa sin una explicación nueva.",
        null,
        { status: "unresolved" },
      ),
      { when: extra.when, cue: extra.cue || "unusual" },
    ),
  ],
});
export const ambient = [
  incident(
    "corridor",
    "Un paso de más",
    "spatial",
    "El pasillo de tu edificio requiere un paso más al volver que al salir. Lo mides con una cinta prestada: las dos longitudes anotadas difieren. A la mañana siguiente ya no hay diferencia.",
    "Mediste una diferencia transitoria de longitud en un pasillo.",
    "Guardar ambas medidas",
    "Devolver la cinta",
  ),
  incident(
    "rain",
    "La lluvia que no moja",
    "material",
    "Una franja de lluvia atraviesa el patio sin dejar húmeda la ropa tendida. El suelo de alrededor sí se moja. Otra vecina señala la misma franja antes de que deje de llover.",
    "Dos personas observaron lluvia que no humedecía una franja del patio.",
    "Comparar lo que vimos",
    "Recoger la ropa",
  ),
  incident(
    "leaf",
    "La hoja todavía verde",
    "biological",
    "Una rama seca sostiene una hoja verde. Al caer, la hoja proyecta una sombra de varios pétalos que no tiene. La guardas un momento sobre papel: la sombra vuelve a ser corriente.",
    "Observaste una discordancia breve entre una hoja y su sombra.",
    "Dibujar la sombra",
    "Dejar la hoja en el jardín",
  ),
  incident(
    "word",
    "Una palabra compartida",
    "cognitive",
    "Dos desconocidos en la fila preguntan por una palabra que no pertenece a la conversación. Ambos creen haberla oído en voz alta; nadie más la oyó. La fila avanza antes de que acuerden cómo escribirla.",
    "Escuchaste dos recuerdos coincidentes de una palabra sin fuente identificada.",
    "Anotar las dos versiones",
    "Dejar pasar a la siguiente persona",
  ),
  incident(
    "glass",
    "El vaso quieto",
    "resonant",
    "Al apoyar un vaso, el agua forma tres círculos sin que la mesa vibre. Otra persona repite el gesto y no ocurre nada. No descubres una técnica que puedas aprender ni reproducir.",
    "Observaste una respuesta aislada del agua que no pudiste reproducir.",
    "Describir el límite",
    "Beber el agua",
  ),
  incident(
    "knock",
    "Antes del golpe",
    "causal",
    "Oyes un golpe en la puerta. Cuando abres, la repartidora tiene la mano levantada y dice que aún no ha llamado. El paquete es el que esperabas; su contenido no tiene nada extraño.",
    "Un sonido pareció preceder al gesto esperado, sin registro independiente.",
    "Preguntar con calma",
    "Firmar la entrega",
  ),
  incident(
    "shadow",
    "La sombra detenida",
    "temporal",
    "La sombra de una antena permanece quieta mientras las demás se mueven. Una fotografía conserva la diferencia. Más tarde todo vuelve a coincidir; nadie puede señalar el instante exacto del cambio.",
    "Una fotografía conservó una sombra discordante durante un intervalo limitado.",
    "Guardar la fotografía",
    "Seguir el camino",
    { note: { scar: "shadow_interval" } },
  ),
  incident(
    "grit",
    "Tierra en el umbral",
    "displacement",
    "Al abrir el pequeño almacén encuentras una línea de arena oscura bajo una puerta sellada. No coincide con la obra de la calle. No hay huellas ni un hueco por el que pasar a otro lugar.",
    "Encontraste material ajeno junto a un umbral, sin una ruta transitable.",
    "Conservar una muestra rotulada",
    "Barrer y anotar el hallazgo",
  ),
  incident(
    "rhythm",
    "El ritmo de la tubería",
    "resonant",
    "La tubería del patio suena: tres golpes, una pausa y dos golpes. El fontanero ha cerrado el suministro y también los oye. No encuentra una avería que explique ese ritmo; al volver el agua, cesa.",
    "Oíste un ritmo de tres golpes y dos golpes sin fuente mecánica identificada.",
    "Anotar el ritmo",
    "Ayudar a recoger las herramientas",
    { note: { motif: "rhythm", legacy: true } },
  ),
  incident(
    "stitch",
    "El hilo abierto",
    "material",
    "En el forro de una chaqueta usada encuentras un trazo sin cerrar, hecho con hilo del mismo color. La costurera lo reconoce como una puntada corriente. Te llama la atención aunque no esconda un mensaje demostrable.",
    "Un trazo abierto en una costura corriente llamó tu atención.",
    "Dibujar el trazo",
    "Arreglar el forro",
    { note: { motif: "mark", legacy: true } },
  ),
  incident(
    "chair",
    "Otra silla",
    "cognitive",
    "Una persona aparta una silla y dice «Todavía hay tiempo para sentarse». La conversación trata de una factura de agua. La frase permanece contigo más tiempo que el resto, sin cambiar lo que esa persona sabe.",
    "Una frase corriente resonó durante una conversación ordinaria.",
    "Aceptar la silla",
    "Agradecer y seguir",
    { note: { motif: "phrase", legacy: true } },
  ),
  incident(
    "echo_wall",
    "La pared que devuelve tarde",
    "spatial",
    "En un patio, una pared devuelve tu saludo cuando ya has salido de él. Quien barre junto a la entrada también lo oye. Al probar de nuevo, solo responde el ruido de la calle.",
    "Dos personas oyeron un eco tardío que no volvió a producirse.",
    "Comparar el intervalo",
    "Dejar la prueba",
  ),
];
export const rare = [
  incident(
    "pale_table",
    "Una mesa sin reflejo",
    "material",
    "Sobre una mesa de trabajo, una pequeña zona deja de reflejar la luz. Puedes tocar la madera y notar su temperatura. La fotografía registra el hueco pálido, no otra habitación. Al guardar las herramientas, vuelve el reflejo.",
    "Una superficie material perdió temporalmente su reflejo sin convertirse en paso a otro lugar.",
    "Guardar la comparación",
    "Terminar el trabajo",
    {
      kind: "rare",
      when: { any: [cap("production"), cap("technical")] },
      note: { legacy: true },
    },
  ),
  incident(
    "weak_signal",
    "La señal menor",
    "resonant",
    "Un instrumento sencillo registra una pulsación que los equipos de mayor alcance filtran como ruido. Alguien con poca potencia puede distinguirla. La lectura no da una respuesta; permite conservar un dato que parecía insignificante.",
    "Una señal débil resultó observable sin requerir alto rango ni gran potencia.",
    "Conservar la lectura sin exagerarla",
    "Solicitar una comprobación",
    {
      kind: "rare",
      when: {
        any: [cap("analysis"), cap("technical"), { type: "rank", value: "E" }],
      },
      note: { legacy: true },
    },
  ),
  incident(
    "open_margin",
    "El margen repetido",
    "cognitive",
    "Un cuaderno de mantenimiento presenta un trazo abierto junto a una fecha. No indica una puerta ni una instrucción. Su forma resulta familiar, pero quien escribió el cuaderno no reconoce ninguna historia detrás de ella.",
    "Un trazo abierto reapareció en un contexto independiente sin transmitir conocimiento a otra persona.",
    "Conservar el contexto",
    "Preguntar por la reparación",
    {
      kind: "rare",
      when: prior("open_mark"),
      note: { motif: "mark", legacy: true },
      cue: "memory",
    },
  ),
  incident(
    "empty_frequency",
    "Una escucha sin destino",
    "displacement",
    "En una prueba de radio se oyen cubiertos, agua y una breve despedida en una lengua que nadie presente identifica. No hay coordenadas ni una petición de ayuda. La señal termina sin que puedas decidir quién estaba al otro lado.",
    "Una escucha recibió sonidos de una vida cotidiana cuyo origen no pudo establecerse.",
    "Guardar la grabación con sus límites",
    "Cerrar la escucha",
    {
      kind: "rare",
      when: { type: "meta-perspective", id: "contact" },
      note: { legacy: true },
      cue: "convergence",
    },
  ),
];
