export const STAGES = [
  { id: "baby", name: "Primeros pasos", min: 0, icon: "sprout" },
  { id: "child", name: "Infancia", min: 3, icon: "sun" },
  { id: "teen", name: "Adolescencia", min: 13, icon: "spark" },
  { id: "young", name: "Juventud", min: 18, icon: "compass" },
  { id: "adult", name: "Adultez", min: 30, icon: "leaf" },
  { id: "elder", name: "Años dorados", min: 60, icon: "sunset" },
];
export const NAMES = [
  "Alex",
  "Valentina",
  "Mateo",
  "Lucía",
  "Simón",
  "Emma",
  "Nicolás",
  "Camila",
  "Sofía",
  "Gabriel",
  "Renata",
  "Emilio",
];
export const CITIES = [
  "Medellín",
  "Bogotá",
  "Ciudad de México",
  "Quito",
  "Lima",
  "Montevideo",
];
export const TRAITS = {
  curious: {
    name: "Mente curiosa",
    icon: "book",
    description: "Aprendes un 30% más con cada actividad.",
    bonus: { intelligence: 8 },
  },
  social: {
    name: "Alma sociable",
    icon: "people",
    description: "Los vínculos crecen más y se desgastan menos.",
    bonus: { charisma: 12 },
  },
  creative: {
    name: "Espíritu creativo",
    icon: "palette",
    description: "Crear te da más habilidad y felicidad.",
    bonus: { creativity: 15 },
  },
  athletic: {
    name: "Corazón atlético",
    icon: "bolt",
    description: "Entrenar rinde más. Envejeces con mejor salud.",
    bonus: { fitness: 12, strength: 12 },
  },
  ambitious: {
    name: "Gran ambición",
    icon: "star",
    description: "Más experiencia laboral; también más estrés.",
    bonus: { discipline: 10 },
  },
  lucky: {
    name: "Buena estrella",
    icon: "clover",
    description: "Un 15% extra de probabilidad en las oportunidades.",
    bonus: { happiness: 5 },
  },
  impulsive: {
    name: "Sin filtro",
    icon: "flame",
    description: "Más carisma, pero gastos cotidianos un 15% mayores.",
    bonus: { charisma: 15, happiness: 8 },
  },
};
export const ORIGINS = {
  humble: {
    name: "Familia trabajadora",
    description: "Poco dinero, mucho ingenio.",
    cash: 200,
    allowance: 100,
    bonus: { discipline: 8 },
  },
  balanced: {
    name: "Un hogar tranquilo",
    description: "Un comienzo con equilibrio.",
    cash: 800,
    allowance: 250,
    bonus: { happiness: 5 },
  },
  wealthy: {
    name: "Una vida cómoda",
    description: "Más oportunidades, mayores expectativas.",
    cash: 3500,
    allowance: 500,
    bonus: { intelligence: 5, happiness: -5 },
  },
};
export const STAT_LABELS = {
  health: "Salud",
  happiness: "Felicidad",
  intelligence: "Inteligencia",
  fitness: "Condición física",
  energy: "Energía",
  stress: "Estrés",
};
export const SKILL_LABELS = {
  technology: "Tecnología",
  creativity: "Creatividad",
  charisma: "Carisma",
  strength: "Fuerza",
  discipline: "Disciplina",
  finance: "Finanzas",
};
export const ACTIVITIES = [
  {
    id: "play",
    name: "Explorar y jugar",
    description: "La curiosidad empieza con las manos llenas de tierra.",
    icon: "sun",
    min: 0,
    max: 17,
    energy: 16,
    effects: { happiness: 7, creativity: 4, intelligence: 2, health: 1 },
  },
  {
    id: "read",
    name: "Un mundo por descubrir",
    description: "Un libro, una idea y un rato de concentración.",
    icon: "book",
    min: 0,
    energy: 18,
    effects: { intelligence: 5, discipline: 3, happiness: -1 },
  },
  {
    id: "train",
    name: "Ponerte en movimiento",
    description: "Cuida tu cuerpo y construye una rutina.",
    icon: "bolt",
    min: 3,
    energy: 25,
    effects: { fitness: 7, strength: 5, health: 5, discipline: 2, stress: -6 },
  },
  {
    id: "create",
    name: "Crear algo tuyo",
    description: "Convierte esa idea en una canción, dibujo o historia.",
    icon: "palette",
    min: 3,
    energy: 20,
    effects: { creativity: 7, happiness: 4, discipline: 1 },
  },
  {
    id: "code",
    name: "Construir con tecnología",
    description: "Aprende a programar resolviendo un problema real.",
    icon: "code",
    min: 10,
    energy: 26,
    effects: { technology: 8, intelligence: 3, stress: 3 },
  },
  {
    id: "budget",
    name: "Poner tus cuentas en orden",
    description: "Aprende a planear antes de gastar.",
    icon: "wallet",
    min: 13,
    energy: 14,
    effects: { finance: 7, discipline: 3, stress: -2 },
  },
  {
    id: "rest",
    name: "Bajar el ritmo",
    description: "Descansar también es avanzar. Recupera energía.",
    icon: "moon",
    min: 0,
    energy: 0,
    effects: { energy: 38, health: 7, happiness: 4, stress: -20 },
  },
  {
    id: "freelance",
    name: "Un proyecto extra",
    description: "Gana $1.200 con tus habilidades; sacrifica descanso.",
    icon: "briefcase",
    min: 18,
    energy: 30,
    requires: { technology: 25 },
    effects: { cash: 1200, technology: 2, stress: 9, happiness: -2 },
  },
];
export const COURSES = [
  {
    id: "self",
    name: "Ruta autodidacta",
    description: "Aprende a tu ritmo con recursos abiertos.",
    years: 2,
    cost: 0,
    min: 13,
    effects: { technology: 6, discipline: 4 },
    icon: "book",
  },
  {
    id: "technical",
    name: "Formación técnica",
    description: "Una ruta práctica hacia el mundo laboral.",
    years: 2,
    cost: 900,
    min: 18,
    effects: { technology: 9, intelligence: 4 },
    icon: "tool",
  },
  {
    id: "university",
    name: "Universidad",
    description: "Estudia ingeniería y abre nuevas puertas.",
    years: 4,
    cost: 2400,
    min: 18,
    requires: { intelligence: 45 },
    effects: { intelligence: 5, technology: 5, discipline: 3 },
    icon: "graduation",
  },
  {
    id: "medicine",
    name: "Medicina",
    description: "Seis años de ciencia, prácticas y vocación.",
    years: 6,
    cost: 3200,
    min: 18,
    requires: { intelligence: 60 },
    effects: { intelligence: 5, discipline: 5 },
    icon: "heart",
  },
  {
    id: "art",
    name: "Escuela de artes",
    description: "Transforma tu creatividad en una profesión.",
    years: 3,
    cost: 1400,
    min: 18,
    requires: { creativity: 25 },
    effects: { creativity: 9, charisma: 3 },
    icon: "palette",
  },
  {
    id: "postgrad",
    name: "Posgrado",
    description: "Especialización para liderar tu profesión.",
    years: 2,
    cost: 3800,
    min: 22,
    degree: "university",
    effects: { intelligence: 7, technology: 5, discipline: 4 },
    icon: "star",
  },
];
export const JOBS = [
  {
    id: "service",
    name: "Asistente de cafetería",
    salary: 13500,
    stress: 6,
    satisfaction: 2,
    icon: "coffee",
    requires: {},
  },
  {
    id: "technician",
    name: "Técnico de sistemas",
    salary: 23000,
    stress: 9,
    satisfaction: 3,
    icon: "tool",
    requires: { technology: 30 },
    degree: "technical",
  },
  {
    id: "developer",
    name: "Desarrollador de software",
    salary: 38000,
    stress: 14,
    satisfaction: 4,
    icon: "code",
    requires: { technology: 55, discipline: 30 },
  },
  {
    id: "engineer",
    name: "Ingeniero de proyectos",
    salary: 42000,
    stress: 15,
    satisfaction: 4,
    icon: "compass",
    requires: { intelligence: 60 },
    degree: "university",
  },
  {
    id: "doctor",
    name: "Profesional de medicina",
    salary: 56000,
    stress: 20,
    satisfaction: 6,
    icon: "heart",
    requires: { intelligence: 70 },
    degree: "medicine",
  },
  {
    id: "artist",
    name: "Artista independiente",
    salary: 26000,
    stress: 8,
    satisfaction: 7,
    icon: "palette",
    requires: { creativity: 55, charisma: 20 },
  },
  {
    id: "athlete",
    name: "Deportista profesional",
    salary: 45000,
    stress: 12,
    satisfaction: 5,
    icon: "trophy",
    requires: { fitness: 80, strength: 65, discipline: 40 },
    maxAge: 45,
  },
  {
    id: "founder",
    name: "Tu propio negocio",
    salary: 48000,
    stress: 23,
    satisfaction: 8,
    icon: "rocket",
    requires: { finance: 45, charisma: 40 },
    cost: 18000,
  },
];
export const HOUSING = {
  family: { name: "Hogar familiar", yearly: 2400, value: 0, cost: 0 },
  rent: { name: "Tu propio apartamento", yearly: 6600, value: 0, cost: 1200 },
  home: { name: "Casa propia", yearly: 2000, value: 85000, cost: 85000 },
};
export const TRANSPORT = {
  walk: { name: "A pie y en bus", cost: 0, yearly: 600, value: 0 },
  bike: { name: "Bicicleta", cost: 400, yearly: 80, value: 200 },
  car: { name: "Automóvil", cost: 9000, yearly: 1800, value: 6000 },
};
export const ACHIEVEMENTS = [
  {
    id: "first",
    name: "El primer capítulo",
    description: "Empieza tu primera vida.",
    icon: "sprout",
    test: (s) => s.history.length > 0,
  },
  {
    id: "graduate",
    name: "El mundo te espera",
    description: "Gradúate de la universidad o medicina.",
    icon: "graduation",
    test: (s) =>
      s.education.degrees.some((d) => ["university", "medicine"].includes(d)),
  },
  {
    id: "home",
    name: "Echar raíces",
    description: "Compra una casa.",
    icon: "home",
    test: (s) => s.housing === "home",
  },
  {
    id: "parent",
    name: "Un nuevo comienzo",
    description: "Forma una familia con hijos.",
    icon: "heart",
    test: (s) => s.relationships.some((r) => r.type === "child"),
  },
  {
    id: "founder",
    name: "A tu manera",
    description: "Crea tu propia empresa.",
    icon: "rocket",
    test: (s) => s.flags.founder,
  },
  {
    id: "wealth",
    name: "Club del millón",
    description: "Alcanza $1.000.000 de patrimonio.",
    icon: "wallet",
    test: (s) => s.peaks.wealth >= 1000000,
  },
  {
    id: "genius",
    name: "Una mente brillante",
    description: "Alcanza 100 de inteligencia.",
    icon: "book",
    test: (s) => s.stats.intelligence >= 100,
  },
  {
    id: "athletic",
    name: "Sin límites",
    description: "Alcanza 100 de condición física.",
    icon: "bolt",
    test: (s) => s.stats.fitness >= 100,
  },
  {
    id: "golden",
    name: "Noventa primaveras",
    description: "Vive hasta los 90 años.",
    icon: "sun",
    test: (s) => s.age >= 90,
  },
  {
    id: "love",
    name: "Toda una vida",
    description: "Cuida una pareja durante 25 años.",
    icon: "people",
    test: (s) =>
      s.relationships.some(
        (r) => r.type === "partner" && r.bond >= 60 && s.age - r.since >= 25,
      ),
  },
  {
    id: "comeback",
    name: "Volver a empezar",
    description: "Saldaste una deuda de más de $10.000.",
    icon: "spark",
    secret: true,
    test: (s) => s.flags.bigDebt && s.debt === 0,
  },
  {
    id: "stargazer",
    name: "Polvo de estrellas",
    description: "Viste la lluvia de estrellas con alguien especial.",
    icon: "star",
    secret: true,
    test: (s) => s.flags.stargazer,
  },
];
