// Approved class concepts from lore/CLASSES.md. Localization, weights and compatibility
// are initial runtime catalog choices, not new immutable lore. Reserved classes stay out.
const ordinary = { common: 1, uncommon: 1, rare: 0.3 };
const specialized = { rare: 1, epic: 1, legendary: 1, mythic: 1 };
const entry = (
  id,
  concept,
  name,
  family,
  rarityWeights,
  affinity,
  resonance,
  capabilities,
  manifestation,
  limitation,
) => ({
  id,
  concept,
  name,
  family,
  rarityWeights,
  affinity,
  resonance,
  capabilities,
  narrativeCapabilities: capabilities.map((tag) => `recognize:${tag}`),
  manifestation,
  limitation,
});
export const CLASSES = [
  entry(
    "warrior",
    "Warrior",
    "Guerrero",
    "combat",
    ordinary,
    ["kinetic"],
    ["organisms"],
    ["physical-reinforcement"],
    "La energía acompaña un movimiento de tu cuerpo.",
    "No concede técnica de combate ni obliga a combatir.",
  ),
  entry(
    "elementalist",
    "Elementalist",
    "Elementalista",
    "magic",
    ordinary,
    ["material"],
    ["minerals"],
    ["elemental-expression"],
    "La materia cercana responde a tu energía.",
    "La respuesta no equivale a dominar todos los elementos.",
  ),
  entry(
    "healer",
    "Healer",
    "Sanador",
    "support",
    ordinary,
    ["vital"],
    ["organisms"],
    ["tissue-support"],
    "Percibes una respuesta reparadora en tejido vivo.",
    "No sustituye el conocimiento médico ni garantiza una curación.",
  ),
  entry(
    "tracker",
    "Tracker",
    "Rastreador",
    "exploration",
    ordinary,
    ["perceptive"],
    ["spaces"],
    ["trace-sensing"],
    "Una huella que antes no veías adquiere presencia.",
    "Percibir una huella no revela toda su historia.",
  ),
  entry(
    "forger",
    "Forger",
    "Forjador",
    "production",
    ordinary,
    ["material"],
    ["minerals"],
    ["material-working"],
    "La energía encuentra dónde una pieza puede cambiar.",
    "Necesita material y aprendizaje; no crea objetos de la nada.",
  ),
  entry(
    "analyst",
    "Analyst",
    "Analista",
    "research",
    ordinary,
    ["perceptive"],
    ["signals"],
    ["pattern-analysis"],
    "Distingues un patrón entre las perturbaciones.",
    "Un patrón no es una explicación infalible.",
  ),
  entry(
    "mana_surgeon",
    "Mana Surgeon",
    "Cirujano de Núcleo",
    "support",
    specialized,
    ["vital"],
    ["organisms", "signals"],
    ["core-repair"],
    "Los canales energéticos se distinguen como una trama reparable.",
    "Reparar Núcleos requiere formación; no garantiza éxito médico universal.",
  ),
  entry(
    "void_cartographer",
    "Void Cartographer",
    "Cartógrafo del Vacío",
    "exploration",
    specialized,
    ["perceptive"],
    ["spaces"],
    ["unstable-geometry"],
    "Percibes una discontinuidad en el espacio del Umbral.",
    "No revela todas las rutas ni la causa de la Convergencia.",
  ),
  entry(
    "anchor",
    "Anchor",
    "Ancla",
    "support",
    specialized,
    ["material", "kinetic"],
    ["spaces"],
    ["local-stabilization"],
    "Un límite cercano deja de oscilar por un instante.",
    "La estabilización es local y temporal, nunca una solución global.",
  ),
  entry(
    "devourer",
    "Devourer",
    "Devorador",
    "combat",
    specialized,
    ["vital"],
    ["organisms"],
    ["temporary-borrowing"],
    "Tu energía conserva un eco ajeno que pronto se apaga.",
    "Adquirir temporalmente propiedades de criaturas derrotadas entraña riesgo de corrupción del Núcleo.",
  ),
  entry(
    "fractured_oracle",
    "Fractured Oracle",
    "Oráculo Fracturado",
    "research",
    specialized,
    ["perceptive"],
    ["signals"],
    ["possible-futures"],
    "Dos desenlaces incompatibles se superponen un instante.",
    "Percibe posibilidades, nunca cuál ocurrirá con certeza.",
  ),
  entry(
    "blood_weaver",
    "Blood Weaver",
    "Tejedor de Sangre",
    "support",
    specialized,
    ["vital"],
    ["organisms"],
    ["biological-processes"],
    "Un proceso vivo responde al hilo de tu energía.",
    "No determina moralidad ni autoriza intervenir sin conocimiento.",
  ),
];
export const CLASS_BY_ID = Object.fromEntries(CLASSES.map((c) => [c.id, c]));
