import { card as c, choice as o } from "./schema.js";
export const EARLY = [
  c(
    "first_light",
    "elena",
    "Aquí estás. No sé hacerlo todo, pero voy a quedarme contigo.",
    o("Buscar su mano", { happiness: 5 }, { bond: 8, behavior: "social" }),
    o("Mirar la ventana", { intelligence: 4 }, { behavior: "curious" }),
    { requires: { max: 0 }, priority: 100, months: 12, pool: "childhood" },
  ),
  c(
    "first_steps",
    "tomas",
    "Te espero al otro lado. Puedes venir solo, o puedo acercarme.",
    o("Pedir sus brazos", { health: 3, happiness: 4 }, { bond: 6 }),
    o("Dar el paso", { fitness: 6, discipline: 3 }, { behavior: "bold" }),
    {
      requires: { min: 1, max: 2 },
      priority: 40,
      months: 12,
      pool: "childhood",
    },
  ),
  c(
    "grandma_song",
    "ines",
    "Tu madre se dormía con esta canción. ¿Otra vez, o inventamos el final?",
    o(
      "Otra vez",
      { happiness: 5 },
      {
        bond: 8,
        flags: ["song"],
        milestone: "Inés te enseñó una canción que nunca olvidaste.",
      },
    ),
    o(
      "Inventar el final",
      { creativity: 7 },
      { flags: ["inventor"], behavior: "curious" },
    ),
    { requires: { max: 5 }, months: 12, pool: "family" },
  ),
  c(
    "mud_shoes",
    "tomas",
    "Podemos saltar en los charcos. Pero esos zapatos son los únicos que tienes.",
    o("Caminar por el borde", { discipline: 5 }, { behavior: "careful" }),
    o(
      "Saltar juntos",
      { happiness: 8, health: -2 },
      { bond: 5, behavior: "bold" },
    ),
    { requires: { min: 2, max: 8 }, pool: "childhood" },
  ),
  c(
    "broken_radio",
    "omar",
    "La radio no habla. ¿Me ayudas a abrirla? Quizá sobren algunos tornillos.",
    o("Escuchar desde aquí", { creativity: 4, happiness: 3 }),
    o(
      "Buscar el destornillador",
      { technology: 8 },
      {
        flags: ["radio"],
        bond: 8,
        follow: [{ id: "radio_reply", months: 144 }],
        milestone: "Ayudaste a Omar a reparar su vieja radio.",
      },
    ),
    { requires: { min: 5, max: 12 }, pool: "childhood", arc: "radio" },
  ),
  c(
    "vera_intro",
    "vera",
    "He guardado este asiento. Si te sientas aquí, tendremos que compartir las galletas.",
    o(
      "Sentarme delante",
      { intelligence: 5, discipline: 2 },
      { flags: ["veraReserved"] },
    ),
    o(
      "Compartirlas",
      { happiness: 5, charisma: 4 },
      {
        bond: 12,
        flags: ["veraClose"],
        milestone: "Vera te guardó un asiento. Así empezó todo.",
      },
    ),
    {
      requires: { min: 6, max: 12 },
      priority: 25,
      pool: "friendship",
      arc: "vera",
    },
  ),
  c(
    "school_drawing",
    "salma",
    "Tu dibujo no se parece al ejemplo. ¿Me cuentas qué está pasando aquí?",
    o("Seguir el ejemplo", { discipline: 5, intelligence: 2 }),
    o(
      "Contar mi historia",
      { creativity: 7, charisma: 2 },
      { behavior: "bold" },
    ),
    { requires: { min: 6, max: 11 }, pool: "school" },
  ),
  c(
    "mother_shift",
    "elena",
    "Hoy trabajo de noche. Puedes dormir en casa de Inés o esperar con papá.",
    o("Ir con Inés", { happiness: 5 }, { flags: ["grandmaTime"] }),
    o("Esperar despierto", { health: -2, intelligence: 3 }, { bond: 6 }),
    { requires: { min: 3, max: 9 }, pool: "family" },
  ),
  c(
    "library_key",
    "salma",
    "La biblioteca necesita a alguien en el recreo. Hay libros que todavía nadie ha abierto.",
    o("Salir a jugar", { fitness: 5, happiness: 4 }),
    o(
      "Quedarme con los libros",
      { intelligence: 8, happiness: -2 },
      { flags: ["library"], behavior: "curious" },
    ),
    { requires: { min: 7, max: 15 }, pool: "school" },
  ),
  c(
    "lost_puppy",
    "omar",
    "El cachorro lleva toda la tarde siguiéndote. En tu casa apenas hay sitio.",
    o("Buscarle otra casa", { charisma: 4 }, { bond: 4 }),
    o(
      "Llevarlo conmigo",
      { happiness: 8, cash: -100, discipline: 3 },
      { flags: ["pet"], milestone: "Un cachorro encontró su casa contigo." },
    ),
    { requires: { min: 7, max: 16 }, pool: "family" },
  ),
  c(
    "family_trip",
    "tomas",
    "Podemos visitar el mar. El dinero era para cambiar mi herramienta de trabajo.",
    o("Dejarlo para después", { finance: 5 }, { behavior: "careful", bond: 3 }),
    o(
      "Hacer el viaje",
      { happiness: 9, cash: -180 },
      { bond: 8, flags: ["sea"] },
    ),
    { requires: { min: 6, max: 16 }, pool: "family" },
  ),
  c(
    "fair_project",
    "salma",
    "Vera quiere presentar tu invento contigo. Tendríais que compartir también el mérito.",
    o("Presentarlo solo", { discipline: 5, stress: 4 }, { behavior: "bold" }),
    o(
      "Hacer equipo",
      { technology: 5, charisma: 4 },
      { flags: ["team"], bond: 5 },
    ),
    { requires: { min: 10, max: 17 }, pool: "school" },
  ),
  c(
    "friend_secret",
    "vera",
    "Me cambio de colegio. No se lo he dicho a nadie. ¿Seguiremos viéndonos?",
    o(
      "No prometer tanto",
      { happiness: -2, discipline: 4 },
      { bond: -4, flags: ["veraDistant"] },
    ),
    o(
      "Cada sábado",
      { happiness: 5 },
      {
        bond: 12,
        flags: ["veraPromise"],
        follow: [{ id: "vera_return", months: 48 }],
        milestone: "Prometiste volver a ver a Vera los sábados.",
      },
    ),
    {
      requires: { min: 10, max: 16, since: { vera_intro: 12 } },
      pool: "friendship",
      arc: "vera",
    },
  ),
  c(
    "father_workshop",
    "tomas",
    "El taller abre los sábados. Podría enseñarte, pero tus amigos van al río.",
    o("Ir al río", { fitness: 4, happiness: 6 }),
    o(
      "Aprender en el taller",
      { technology: 8, discipline: 4, happiness: -2 },
      {
        flags: ["workshop"],
        bond: 8,
        follow: [{ id: "workshop_offer", months: 60 }],
        milestone: "Empezaste a aprender en el taller de Tomás.",
      },
    ),
    { requires: { min: 11, max: 16 }, pool: "career", arc: "workshop" },
  ),
  c(
    "first_phone",
    "elena",
    "Podemos comprar un teléfono usado. O arreglar la bicicleta y esperar otro año.",
    o("Arreglar la bicicleta", { fitness: 7, cash: -100 }),
    o(
      "Elegir el teléfono",
      { technology: 5, charisma: 3, cash: -250 },
      { behavior: "social" },
    ),
    { requires: { min: 10, max: 16 }, pool: "childhood" },
  ),
  c(
    "exam_night",
    "salma",
    "El examen es mañana. Te has preparado; ahora tienes que decidir cuándo parar.",
    o("Cerrar el cuaderno", { health: 5, stress: -8 }),
    o(
      "Una hora más",
      { intelligence: 7, health: -3, stress: 5 },
      { behavior: "careful" },
    ),
    { requires: { min: 12, max: 17 }, pool: "school" },
  ),
  c(
    "noa_intro",
    "noa",
    "Hay una azotea desde la que se ve toda la ciudad. ¿Te enseño?",
    o("Otro día", { discipline: 4 }, { flags: ["noaWait"] }),
    o(
      "Vamos",
      { happiness: 6, charisma: 3 },
      {
        bond: 8,
        flags: ["noaMet"],
        milestone: "Noa te mostró la ciudad desde una azotea.",
      },
    ),
    {
      requires: { min: 16, max: 26 },
      pool: "romance",
      arc: "noa",
      priority: 8,
    },
  ),
  c(
    "late_home",
    "elena",
    "Dijiste que volverías antes de las diez. Solo quiero saber si estás bien.",
    o("Contarlo todo", { stress: -5 }, { bond: 8, behavior: "social" }),
    o(
      "Pedir espacio",
      { happiness: 5, charisma: 4 },
      { bond: -7, behavior: "bold", flags: ["independent"] },
    ),
    { requires: { min: 14, max: 18 }, pool: "family" },
  ),
  c(
    "scholarship_interview",
    "salma",
    "Puedo recomendarte para una beca. Quieren que estudies lejos de casa.",
    o("Quedarme cerca", { happiness: 5 }, { bond: 4, flags: ["localRoute"] }),
    o(
      "Enviar la solicitud",
      { stress: 5, intelligence: 4 },
      {
        flags: ["scholarship"],
        milestone: "Conseguiste una beca para seguir estudiando.",
      },
    ),
    {
      requires: { min: 16, max: 19, skills: { intelligence: 45 } },
      pool: "education",
      arc: "education",
    },
  ),
  c(
    "band_rehearsal",
    "vera",
    "Nos falta alguien para el concierto. No hace falta tocar perfecto; sí venir a todos los ensayos.",
    o("Ser público", { happiness: 5 }, { bond: 3 }),
    o(
      "Subir al escenario",
      { creativity: 9, charisma: 5, stress: 4 },
      { flags: ["band"], behavior: "bold" },
    ),
    { requires: { min: 13, max: 24 }, pool: "friendship" },
  ),
  c(
    "school_race",
    "salma",
    "Has corrido muy bien. El equipo entrena cuando se reúne el club de dibujo.",
    o("Quedarme dibujando", { creativity: 8 }),
    o(
      "Entrenar con el equipo",
      { fitness: 10, strength: 8, discipline: 4 },
      { flags: ["teamSport"] },
    ),
    { requires: { min: 10, max: 18 }, pool: "school" },
  ),
  c(
    "own_money",
    "omar",
    "Necesito ayuda con las cajas. Puedo pagarte o enseñarte a reparar una pantalla.",
    o("Elegir el pago", { cash: 250, strength: 3 }),
    o(
      "Aprender a repararla",
      { technology: 10, discipline: 3 },
      { behavior: "curious" },
    ),
    { requires: { min: 13, max: 19 }, pool: "career" },
  ),
  c(
    "school_protest",
    "vera",
    "Van a cerrar nuestro club. Hay una reunión, justo antes del examen que te preocupa.",
    o("Preparar el examen", { intelligence: 6 }, { bond: -3 }),
    o(
      "Ir a la reunión",
      { charisma: 8, stress: 4 },
      { bond: 8, flags: ["advocate"] },
    ),
    { requires: { min: 14, max: 19 }, pool: "school" },
  ),
  c(
    "grandma_box",
    "ines",
    "Esta caja tiene cartas que nunca envié. ¿Las leemos o me ayudas a guardarlas?",
    o(
      "Respetar la caja",
      { discipline: 4 },
      { bond: 8, flags: ["keptLetters"] },
    ),
    o(
      "Leerlas juntos",
      { intelligence: 5, happiness: 3 },
      {
        bond: 10,
        flags: ["readLetters"],
        follow: [{ id: "grandma_echo", months: 180 }],
        milestone: "Leíste con Inés las cartas que nunca envió.",
      },
    ),
    { requires: { min: 8, max: 20 }, pool: "family", arc: "letters" },
  ),
  c(
    "friend_reunion",
    "vera",
    "No nos vemos como antes. Tengo libre esta tarde, aunque sé que tenías otros planes.",
    o(
      "Mantener mis planes",
      { discipline: 4 },
      { bond: -4, flags: ["veraDistant"] },
    ),
    o(
      "Hacerle un hueco",
      { happiness: 6, stress: -4 },
      { bond: 12, behavior: "social" },
    ),
    {
      requires: { min: 13, max: 28, since: { vera_intro: 24 } },
      pool: "friendship",
    },
  ),
  c(
    "first_vote",
    "tomas",
    "Esta será tu primera elección. Puedo contarte lo que pienso, si quieres.",
    o("Escucharlo", { charisma: 4 }, { bond: 5 }),
    o(
      "Investigar por mi cuenta",
      { intelligence: 6, discipline: 3 },
      { behavior: "curious" },
    ),
    { requires: { min: 18, max: 19 }, pool: "life" },
  ),
  c(
    "leave_home",
    "elena",
    "He visto un apartamento pequeño. Te echaría de menos, pero no quiero que te quedes por mí.",
    o("Un poco más aquí", { happiness: 3 }, { bond: 6 }),
    o(
      "Probar por mi cuenta",
      { stress: 5 },
      {
        operation: "rent",
        flags: ["independent"],
        milestone: "Saliste del hogar familiar.",
      },
    ),
    {
      requires: { min: 18, max: 32, housing: "family", cash: 1200 },
      pool: "money",
      arc: "home",
    },
  ),
  c(
    "farewell_school",
    "salma",
    "Ya no necesitas que te diga qué hacer. ¿Qué vas a echar más de menos?",
    o("A las personas", { charisma: 6 }, { behavior: "social" }),
    o(
      "Todo por aprender",
      { intelligence: 5, discipline: 4 },
      { behavior: "curious" },
    ),
    { requires: { min: 18, max: 20 }, priority: 12, pool: "education" },
  ),
  c(
    "old_promise",
    "vera",
    "Aún guardo aquella entrada del concierto. Podríamos ir al siguiente, si sigue siendo nuestro plan.",
    o("Dejarlo como recuerdo", { discipline: 3 }, { bond: -4 }),
    o("Comprar dos entradas", { happiness: 7, cash: -150 }, { bond: 12 }),
    { requires: { min: 20, max: 35, flags: ["band"] }, pool: "friendship" },
  ),
  c(
    "school_found",
    "salma",
    "Han encontrado tu cuaderno en la biblioteca. Otra persona ha seguido escribiendo donde lo dejaste.",
    o("Recuperarlo", { creativity: 5 }, { flags: ["notebook"] }),
    o(
      "Dejar que continúe",
      { happiness: 5, charisma: 3 },
      {
        flags: ["sharedNotebook"],
        follow: [{ id: "notebook_future", months: 180 }],
      },
    ),
    {
      requires: { min: 18, max: 25, flags: ["library"] },
      pool: "education",
      arc: "notebook",
    },
  ),
];
